name: Run testes
on: 
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Node.js environment
        uses: actions/setup-node@3.6.0
        with: 
          node-version: 16.13.x
          cache: yarn
      - name: Install dependencies
        run:  |
          yarn cache clean
          yarn install --network-concurrency 1
      - name: Running tests
        run: yarn test